config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"

  devise_for :users
  resources :users, :only => [:show]
  resources :events
  
  resources :events do
    resources :orders
  end
  

  #resources :orders, only: [:new, :create]
  




  # get 'users/sign_out', to: 'devise/sessions/users#destroy'

  
  #get 'devise/registrations/new', to: 'devices/registrations#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # after_create :welcome_event_send
  
  belongs_to :participant, class_name: "User"
  belongs_to :event

  # def welcome_event_send
  #   AttendanceMailer.welcome_event_email(self.participant, self.event).deliver_now #appel le mailer UserMailer et l'envoi direct
  # end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :administrator, class_name: "User"

  has_many :attendances
  has_many :participants, through: :attendances, class_name: "User"

validates :start_date, #:start_date_future,
presence: true
validates :duration,
  presence: true
validates :title,
  presence: true,
  length: { in: 5..140 }
validates :description,
  presence: true,
  length: { in: 5..1000 }
validates :price,
  presence: true,
  length: { in: 3..1000 }
validates :location,
  presence: true

# def start_date_future
#   errors.add(:start_date, ('This event must be in the future ')) unless start_date > DateTime.now
# end

# validate :duration_length
# def duration_length
#   errors.add(:duration, 'This event must be a multiple of 5 ') unless duration % 5 == 0 && duration > 0
# end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send
   
    has_many :events, foreign_key: 'administrator_id'
    has_many :attendances, foreign_key: 'participant_id'
    has_many :events, through: :attendances
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now #appel le mailer UserMailer et l'envoi direct
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @num_participant = Attendance.where(event_id: params[:id]).count
    @name_participant = Attendance.where(event_id: params[:id])
  end

  def new
    @event = Event.new
  end
 
  def create
     @event = Event.new(params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :administrator_id))
     #@event.administrator_id = current_user.id    
     if @event.save
      redirect_to event_path(@event), notice: "Evènement créé"
    else
      render :new
    end  
  end

  def edit
  @event = Event.find(params[:id])
  end

  def update
  only_user?(current_user)
  @event = Event.find(params[:id])
  if @event.update(params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :administrator_id))
    redirect_to event_path(@event), notice: "Evenement mis à jour"
  else
    render :edit
  end
  end

  def destroy
  only_user?(current_user)
  @event.destroy
  redirect_to root, notice: "Evenement détruit"
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new

    @user = current_user
    @product = Event.find_by(id: params[:event_id])
    @amount = @product.price
    @stripe_amount = (@amount * 100).to_i
  end

  def create
    # Before the rescue, at the beginning of the method  

    @user = current_user
    @product = Event.find_by(id: params[:event_id]) #Product.first
    @amount = @product.price
    @stripe_amount = (@amount * 100).to_i

    begin 
    
      customer = Stripe::Customer.create({  
      email: params[:stripeEmail],  
      source: params[:stripeToken],  
      }) 
      
      charge = Stripe::Charge.create({  
      customer: customer.id,  
      amount: @stripe_amount,  
      description: "Achat d'un produit",  
      currency: 'eur',  
      })
      
      rescue Stripe::CardError => e  
      flash[:error] = e.message  
      redirect_to new_order_path  
    
    end
    #After the rescue, if the payment succeeded

    Attendance.create(event_id: @product.id,
      participant_id: current_user.id)
  end


end


# Attendance.create(event_id: @product.id,
#   participant_id: current_user.id,
#   stripe_customer_id: customer.id)

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @events = Event.where(administrator_id: (params[:id]))
    @user = User.find(params[:id])
  end

  # def edit
  # end

  # def update
  #   if @user.update(user_params)
  #     redirect_to @user, notice: "Vos informations ont bien été mises à jour."
  #   else
  #     render :edit
  #   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def already_subscribed?(event)
        event.participants.each do |participant|
            puts " Participant: #{participant.id}"
            puts " current: #{current_user.id}"
            if participant.id == current_user.id
                return true
            end
        end
        false
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<%= form_with model:@event ,url: event_path(@event), method: :put do |form| %>
  <div class="form-group">
  <div class="field">
    <%= form.label :Titre %>
    <%= form.text_field :title, placeholder:"texte", class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_area :description, size:"50x2", class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :Date_de_début %>
    <%= form.datetime_local_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :Durée %>
    <%= form.number_field :duration, in:5..60, step:5, class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label :Lieu %>
    <%= form.text_field :location, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :Prix %>
    <%= form.number_field :price, in:1..1000, step:1, class:"form-control" %>
  </div>

  <%= form.hidden_field :administrator_id, :value => current_user.id, class:"form-control" %>

  <button type="submit" class="btn btn-primary">Submit</button>

<%end%>

  </div>
</form>

app/views/events/index.html.erb
<ul>
  <% if user_signed_in? %>

  <a <%= link_to "Tu peux créer ton évènement ici", new_event_path %> </a>

  <p> </p>


     <p> voici la liste des évènements </p>


 <%= @events.each do |event| %>
<div class="card" style="width: 18rem;">
  <%# <img class="card-img-top" src="..." alt="Card image cap"> %>
  <div class="card-body">
    <h5 class="card-title"> <%= event.title %> </h5>

    <p class="card-text"> <%=  event.description %> </p>
    <a <%= link_to "accéder à la page de l'évènement", event_path(event) %> 
    </div>
       </div>
        <p> </p>
    <% end %>

     
  






  <% else %>
      <p> Veuillez vous connecter pour accéder à la liste des évènements </p>

  <% end %>
</ul>

app/views/events/new.html.erb
<%= form_with model:@event ,url: events_path, method: :post do |form| %>
  <div class="form-group">
  <div class="field">
    <%= form.label :Titre %>
    <%= form.text_field :title, placeholder:"texte", class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_area :description, size:"50x2", class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :Date_de_début %>
    <%= form.datetime_local_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :Durée %>
    <%= form.number_field :duration, in:5..60, step:5, class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label :Lieu %>
    <%= form.text_field :location, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :Prix %>
    <%= form.number_field :price, in:1..1000, step:1, class:"form-control" %>
  </div>

  <%= form.hidden_field :administrator_id, :value => current_user.id, class:"form-control" %>

  <button type="submit" class="btn btn-primary">Submit</button>

<%end%>

  </div>
</form>

app/views/events/show.html.erb
<h1><%= @event.title%></h1>
<p class="m5 p3 xshadow border border-light"><%= @event.description %></p>
<p class="m5 p3 xshadow border border-light"> la localisation est à <%= @event.location %></p>
<p class="m5 p3 xshadow border border-light"> le prix est <%= @event.price %></p>
<p><em class='text-grey'> le mail de l'organisateur est <%= @event.administrator.email %> </em></p>
<p><em class='text-grey'> le nombre de participant est <%= @num_participant %> </em></p>

 <div>
 <%= @event.participants.each do |participant| %>
    <p> l'email des participants est : <%= participant.email %> </h5> 
    <p> le nom des participants est: <%= participant.first_name %> </h5> </p>
    </div>
    <% end %>



<% if current_user.id == @event.administrator.id %>
  <%= link_to 'Modifier', edit_event_path(@event), class: "btn btn-primary" %>
  <%# <%= link_to 'Invités', participations_path(id: @event.id), class: "mt-3 btn btn-primary" %> %>
<% else %>
  <% unless already_subscribed?(@event) %>
    <%= link_to "S'inscrire et payer" , new_event_order_path(@event.id), class: "btn btn-primary mb-3"%>
  <% end %>
<% end %>
  <p> <%= link_to 'Retour', events_path, class: "btn btn-secondary mb-3"%> </p>

app/views/layouts/application.html.erb
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<html>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" >Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" <%= link_to "Accueil", root_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  <%= link_to "Nouvel évènement", new_event_path %>  </a>
      </li>
      
      <% if user_signed_in? %>

       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon profil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Mon profil", current_user, class:"dropdown-item" %> 
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %> 
        </div>
      </li>

      <% else %>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'inscrire / Se connecter
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%= link_to "S'inscrire", new_user_registration_path %> </a>
          <a class="dropdown-item" <%= link_to "Se connecter", new_user_session_path %> </a>
        </div>
      </li>

      <% end %>

      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


  <body>
    <%= yield %>
  </body>
   
</html>



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

app/views/orders/create.html.erb
<h1>Votre paiement est confirmé.</h1>
<h2>Merci <%= @user.first_name %> pour votre achat de <strong><%= @amount %> €</strong> !</h2>
<p>Un email vous a été envoyé à <%= @user.email %> avec le récapitulatif de votre commande.</p>

app/views/orders/new.html.erb
<h1>Bienvenue sur la page de paiement, <%= @user.first_name %> !</h1>
<p>Vous avez choisi le produit <%= @product.title %>.</p>

<%= form_tag event_orders_path do %>  
<article>  
  <% if flash[:error].present? %>  
    <div id="error_explanation">  
      <p><%= flash[:error] %></p>  
    </div>  
  <% end %> 

  <label class="amount">  
      <span>Son prix est de : <%= @amount %> €</span> 
  </label>  
</article>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"  
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>" 
    data-description="Achat d'un produit"  
    data-amount=<%= @stripe_amount %>
    data-currency="eur"
    data-locale="auto">   
</script>  
<% end %>

app/views/users/show.html.erb
<ul>

<h1><%= @user.first_name %></h1>
<h1><%= @user.last_name %></h1>
<h1><%= @user.description %></h1>

<%= @user.email %>

  <a <%= link_to "Tu peux modifier ton mot de passe ici", edit_user_registration_path %> </a>

<a> ci_dessous les évènements que tu as créé </a>
 <%= @events.each do |event| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> <%= event.title %> </h5>

    <p class="card-text"> <%=  event.description %> </p>
    <a <%= link_to "accéder à la page de l'évènement", event_path(event) %> 
 
    </div>
       </div>
        <p> </p>
               <% end %>



</ul>